### ISSUE TITLE
Browsing Windows folders doesn't work

### ISSUE THREAD

**Issue by jkane001** [winterDroid/android-drawable-importer-intellij-plugin#101]
When I go to import a file, all I see is my list of drives, all showing only the files that are in the root - no folders within. The only way I can import images is by dragging from Windows Explorer into the window. This is true on 2 separate computers, one running Windows 7, the other running Windows 10.

**Comment by winterDroid** [comment]
This should be fixed by #94. I released a new version with that fix yesterday (0.3.3). Please check whether you are on that version.

**Comment by jkane001** [comment]
I got the update today, and yes, it does fix it, thanks! I do have a new
request though (some people are never happy, right?). Could you make the
file chooser multi-selectable?

**Comment by winterDroid** [comment]
Cool. I would like to get Multi-Selection working as well - just created #103. As a workaround you can select the whole folder ;)
