### ISSUE TITLE
0.3.3 Update Not Downloading

### ISSUE THREAD

**Issue by chipset95** [winterDroid/android-drawable-importer-intellij-plugin#104]
I have tried downloading the 0.3.3 update from the plugins repository in Android Studio as well as from the website but both fail. 
![workspace 1_001](https://cloud.githubusercontent.com/assets/6591617/10844991/40cda28c-7f2a-11e5-9629-95a49ad04a9b.png)
I'm stuck with issue #94 

I'm on Ubuntu Gnome 14.04.3 64 bit with 0.3.2 version of this plugin

**Comment by winterDroid** [comment]
Mmh but this has nothing to do with my plugin. Did you try to download the zip via that URL and use "Install plugin from disk" afterwards? You can download the zip also here: https://github.com/winterDroid/android-drawable-importer-intellij-plugin/releases/download/0.3.3/android-drawable-importer-intellij-plugin-0.3.3.zip

**Comment by chipset95** [comment]
Thanks for the quick reply. I did try to download it from the jetbrain repository URL. I'll try this link now.

**Comment by chipset95** [comment]
This link is failing too @winterDroid

**Comment by winterDroid** [comment]
@chipset95 I guess then it has something to do with your internet connection. For me both links work..

**Comment by chipset95** [comment]
I'll try it later then. Thanks.
