### ISSUE TITLE
Hope to set the "Target-Root" automatic in Android Studio

### ISSUE THREAD

**Issue by Syehunter** [winterDroid/android-drawable-importer-intellij-plugin#105]
When I tried to import a folder with images， I had to edit their Target-Roots one by one.If I don't do this there will be noting happen on clicking the "Ok".

This doesn't feel very well, hope to fix it with "android-res" folder automatic.

P.S. I'm not very good at English and hope you could know what I mean.

**Comment by winterDroid** [comment]
Yeah this can be improved. A workaround is if you import first one image and specify there the target root. Afterwards this should be used as default for that project.
