### ISSUE TITLE
Resizing 9 patched images cause problem with transparency on image

### ISSUE THREAD

**Issue by vdubedout** [winterDroid/android-drawable-importer-intellij-plugin#114]
This morning when we imported a batch of 9 patch in xxxhdpi to xxhdi -> mdpi, a light grey shadow was merged with the main image that was mostly white.

I have to find some time to look into this deeper.

Thanks for your lib it saves us so much time, our designers loves it :)

**Comment by winterDroid** [comment]
Yeah scaling 9-patches is basically not 100% reliable, due to the difference in scaling algorithms for the border and the main image. You need to check the different images afterwards..
