### ISSUE TITLE
grey600 option removed from material icons

### ISSUE THREAD

**Issue by stephenmcbride** [winterDroid/android-drawable-importer-intellij-plugin#125]
Hi, first off thanks for creating the plugin - it works really well! I just updated to the latest plugin version and the only colours available for material icons are white or black. Grey600 used to be a colour option before I updated the plugin, any possibility of putting this back in? Thanks

**Comment by winterDroid** [comment]
There are different colors for different assets available. So you can't expect that grey600 is available for every asset.. If you found one where it should be available let me know and I can check

**Comment by stephenmcbride** [comment]
Ah right, I was under the impression that the plugin was able to dynamically change the imported icon's colour. Thanks for getting back to me so quickly!

**Comment by DarkNormal** [comment]
Just as a note - it seems like grey600 is no longer available for any icons, I have old icons imported which definitely had the option but now they don't. 
Using
`.setAlpha(128);`
on the drawable achieves the same effect however.
