### ISSUE TITLE
Get the Target-Root Automatically

### ISSUE THREAD

**Issue by feinstein** [winterDroid/android-drawable-importer-intellij-plugin#135]
I opened a bunch of pictures and all of them came with the Target-Root column empty. I had to click the `Edit` button and `OK` for all of them just to get the Target-Root filled, and I tried to just run it with all of them empty and none of the pictures were added.

![captura_de_tela_040116_124819_am](https://cloud.githubusercontent.com/assets/8120472/14197365/c8b9ed80-f7a3-11e5-9b8a-42716eef32d6.jpg)

**Comment by dhiraj** [comment]
Yes, it would be so much better if the res root was auto-filled? Is there even any other place that we can import and have Android Studio work with it?

**Comment by winterDroid** [comment]
Should be fixed with last release by #150
