### ISSUE TITLE
Importing all files from a folder saves them to root folder

### ISSUE THREAD

**Issue by anti43** [winterDroid/android-drawable-importer-intellij-plugin#141]
Importing one file with the batch importer works, more files are saved to c:\\<android drawablefolder names>

**Comment by hajeriwalid** [comment]
Same behaviour on Android Studio 2.0

**Comment by novikk** [comment]
+1

**Comment by winterDroid** [comment]
I guess this is caused by an empty target root folder. Please verify that the root folder is filled. Will close this since it seems to be a duplicate of #135
