### ISSUE TITLE
 IOException

### ISSUE THREAD

**Issue by TannerS** [winterDroid/android-drawable-importer-intellij-plugin#142]
Running off fedora, I get this when attempting to select a group of images for the  Batch Drawable Import

1:45:37 PM Plugin Error: Android Drawable Importer threw an uncaught IOException. Disable Plugin
1:45:37 PM IOException: Unable to create directory /drawable-xxxhdpi

**Comment by pompobit** [comment]
same issue on ubuntu 15.04 and Android studio 2.1.2

**Comment by mp205** [comment]
same on OSX El Capitan, Android Studio 2.1.2

**Comment by TannerS** [comment]
I was able to get it to work by selecting a different output folder, like the desktop and copying in the files manually

**Comment by winterDroid** [comment]
Should be fixed with last release by #150

**Comment by lectricas** [comment]
not working...
![drawableimportererror](https://cloud.githubusercontent.com/assets/8782219/21466082/3168949a-c9d5-11e6-89f8-847c53674547.png)
