### ISSUE TITLE
Target root is empty by default on batch import

### ISSUE THREAD

**Issue by oldergod** [winterDroid/android-drawable-importer-intellij-plugin#144]
First, thanks for this amazing plugin.

# Problem

When I do a Batch Drawable Import, the target root is empty and I need to set it for each files.

# Demo

![batch_import](https://cloud.githubusercontent.com/assets/1767669/18259211/801954ee-741c-11e6-9182-ab98b79bb600.gif)

Is it as expected? Is there something I can do to fix it?

**Comment by winterDroid** [comment]
This is a duplicate of #135
