### ISSUE TITLE
Android Studio 2.2.1, not working

### ISSUE THREAD

**Issue by ArthurSav** [winterDroid/android-drawable-importer-intellij-plugin#149]
The plugin doesn't work with Android Studio 2.2.1. Worked well with AS2.0 if i remember correctly

**Comment by Nava2** [comment]
Confirmed as well:

```
Android Studio 2.2
Build #AI-145.3276617, built on September 15, 2016
JRE: 1.8.0_76-release-b03 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by AngryITGuy** [comment]
Does "not working" mean that on restart of IDE to complete install, you never get past the splash screen ? Then yes, it's not working, AS 2.2.2

**Comment by ArthurSav** [comment]
The exact issue was that the 'add' button, which displays the image picker, was non responsive.
As of AS 2.3 the issue has been resolved and the plugin works correctly.
