### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by xu6148152** [winterDroid/android-drawable-importer-intellij-plugin#18]
How can I install it into Intellij idea?

thank you

**Comment by winterDroid** [comment]
What do you mean? How to install? See https://www.jetbrains.com/idea/help/installing-updating-and-uninstalling-repository-plugins.html

**Comment by winterDroid** [comment]
Will close the issues - reopen it if you have additional questions

**Comment by xu6148152** [comment]
Thank you
