### ISSUE TITLE
Infinite horizontal scroll in settings window

### ISSUE THREAD

**Issue by jdzuri** [winterDroid/android-drawable-importer-intellij-plugin#41]
Hi,

After the last update it's impossible to set the android or material icons assets home because the windows scroll horizontaly all time. This causes that I can't click the selector input file directories to set them.

While the bug is fixed, how I can set the assets home directories manually?

Software info:
- SO: XUbuntu 14.04
- Android Studio: 1.0.2

**Comment by calindotgabriel** [comment]
I endorse this. I have the same specs and problem.

**Comment by winterDroid** [comment]
I saw this once. A workaround was to open another dialog and afterwards the
one you wanted..
Am 01.02.2015 20:34 schrieb "Calin Gabriel" <notifications@github.com>:

**Comment by jdzuri** [comment]
The error always occurs, whether first go to another dialog or anything else.

Can not insert the routes of the assets directly in a configuration file?

**Comment by winterDroid** [comment]
Maybe to fix this I will just add the possibility to add text directly to the text field. It seems that this is an issue with AndroidStudio (happens just there). I just tried it again. It happened when I wanted to open the dialog the first time, afterwards I closed the settings and reopened them. Now the dialog showed up fine for me.

**Comment by jdzuri** [comment]
In my case the infinite scroll trouble always appears. I tried to open and close the settings dialog several  times, clicking over severals sections too and it isn't fixed.

I fix this manually adding the asset paths into the options.xml file of android studio. In my case:
```
<property name="assetPath_ANDROID_ICONS" value="file://$USER_HOME$/projects/icons/androidicons-1.0/assets" />
<property name="assetPath_MATERIAL_ICONS" value="file://$USER_HOME$/projects/icons/material-design-icons-1.0.1" />
```

**Comment by poupougnac** [comment]
I'm also stuck on this issue. I can not fix this manually, the jdzuri trick don't do anything and line are suppressed after starting Android Studio. I can not use the plugin.

**Comment by tajchert** [comment]
@jdzuri solution works - you can import icons to projects but still doesn't solve problem with expanding textbox (even thus it is with text).
Android Studio 1.3.

**Comment by Ph1b** [comment]
This is super annyoing. Cant click on the button.

**Comment by mintux** [comment]
Manual solution doesn't work for me i have added these lines:
    <property name="assetPath_ANDROID_ICONS" value="/home/mrg/Android/material-design-icons-master/assets" />
<property name="assetPath_MATERIAL_ICONS" value="/home/mrg/Android/material-design-icons-master" />

into .AndroidStudio1.3/config/options/options.xml
But i have gotten this error: 
![selection_267](https://cloud.githubusercontent.com/assets/3824913/9231176/06e456a0-413c-11e5-9721-e6fbd70564fb.jpg)

And in setting is scrolling:
![selection_268](https://cloud.githubusercontent.com/assets/3824913/9231212/35619a92-413c-11e5-918b-e5407504e0c0.jpg)

Any idea?
Linux Mint 17.2
Android Studio 1.3

**Comment by gokberkyagci** [comment]
I find the solution in the end. Open "Android Drawable Importer" and than click tab key 3 times finally click space key and select your icon folder.

**Comment by vanla** [comment]
gokberkyagci, thanks a lot, it worked! Should add it as a (temporary) solution to this bug
