### ISSUE TITLE
Installation: folder selection. Which folders?

### ISSUE THREAD

**Issue by lordthistle** [winterDroid/android-drawable-importer-intellij-plugin#44]
I am quite stupid, so forgive me. I am also a novice Android programmer.

I cannot understand these two sentences:

1) "Please select the folder that is probably called "assets" and contains for example black ... "
Which folder should I select? Is it related to the specific project? Is it global for Android Studio

2) Please select the root folder after extracting the archive or cloning the repo. This folder ...
Which repo should I clone or extract?

I installed this plugin while looking for some icons to use. Someone suggested to use this 'importer', but I blocked as soon as I realized I could not understand the only two sentences.

**Comment by winterDroid** [comment]
The folder that you mentioned in (1) is the folder, after you extracted the AndroidIcons pack from https://github.com/opoloo/androidicons/releases/tag/v1.0 - so this is not project specific.
The repo mentioned in (2) is this one https://github.com/google/material-design-icons/releases

Maybe you should have tried to use the download buttons ;)
