### ISSUE TITLE
Drawable Importer menu not showing for modules

### ISSUE THREAD

**Issue by StelianMorariu** [winterDroid/android-drawable-importer-intellij-plugin#45]
The menu options to create new drawables do not appear when right-clicking an android module.
Sample project : https://www.dropbox.com/s/0xh0wl8v19mznup/DrawableImporterTest.rar?dl=0

![dr2](https://cloud.githubusercontent.com/assets/1908415/6125972/492d3f20-b124-11e4-912f-d14e892bc101.png)

**Comment by sergei-okhotnyi** [comment]
+1 to this issue, we have most of our resources within Android Module

**Comment by bahacan19** [comment]
+1

**Comment by winterDroid** [comment]
Should be fixes with PR #53
