### ISSUE TITLE
Settings ubuntu 14.04

### ISSUE THREAD

**Issue by yoavst** [winterDroid/android-drawable-importer-intellij-plugin#49]
The path box become bigger and bigger and unselectable (In settings) :(

**Comment by norx85** [comment]
Same form me on windows 7 and android studio 1.1

**Comment by yoavst** [comment]
also happens on 15.04, so it is problem with 1.1

**Comment by MichaelArchangel** [comment]
Same on windows 7 and android studio 1.0.1...

**Comment by FeanilKaenor** [comment]
Same on Windows 8 and Android Studio 1.2.1.1

**Comment by adaneam** [comment]
Facing same issue in AS 1.3 and windows 8.1. Cannot specify root folders. Is there a way to specify these by manually editing a config file or something?

**Comment by felixMada** [comment]
Same here on ubuntu 14.04 and Android Studio 1.1.0

**Comment by pincopallino93** [comment]
Same on Debian with GNOME and Android Studio 1.3.2.
Any manual solution?
