### ISSUE TITLE
Set path for material icon

### ISSUE THREAD

**Issue by pincopallino93** [winterDroid/android-drawable-importer-intellij-plugin#51]
I don't understand how add path for Material Icon.. I tried in this way but it doesn't work.
![Screen1](http://i57.tinypic.com/2n8a42g.png)
![Screen2](http://i61.tinypic.com/2meebdg.png)

What can I do?

**Comment by winterDroid** [comment]
Open Preferences -> Other settings -> Android Drawable Importer
![untitled](https://cloud.githubusercontent.com/assets/1552225/6939314/b94d714e-d86b-11e4-8dde-69da707c4a8b.png)
