### ISSUE TITLE
Being trolled by the settings page

### ISSUE THREAD

**Issue by GNima** [winterDroid/android-drawable-importer-intellij-plugin#57]
I hope the gif below is self explanatory:

![get rekt](http://i.gyazo.com/9a25a8e4b56661ab0abb4839056cab80.gif)

:bowtie:

**Comment by tomrozb** [comment]
+1 The same issue in Android Studio 1.2 RC2

**Comment by tomrozb** [comment]
Duplicate #49

**Comment by winterDroid** [comment]
Duplicate #49
