### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by jwir3** [winterDroid/android-drawable-importer-intellij-plugin#58]
I'd really like to add to this plugin. Namely, it was so useful that I was thinking about picking up a couple of tickets. Unfortunately, the intellij documentation for plugin development is behind the times. Even worse, the android studio plugin development docs are nonexistent (that I can find). 

If you could post some build instructions to the wiki or in the readme, I would be happy to contribute to this project.

**Comment by winterDroid** [comment]
I'm currently working on a pretty big refactoring and hope to get this done soon. I will update the readme in that update with the build instructions.
