### ISSUE TITLE
Support Material Design Vector Drawables

### ISSUE THREAD

**Issue by benpye** [winterDroid/android-drawable-importer-intellij-plugin#59]
With the new Material Design 2.0 icon pack, vector drawables are now supported. These should be added to the list of dimensions available so that the plugin can import this type of icon. They are in the folder drawable-anydpi-v21 and are supported on 5.0 and later.

**Comment by ligi** [comment]
This is now especially important as VectorDrawableCompat is released

**Comment by winterDroid** [comment]
@ligi I know. Hopefully I get it done soon.

**Comment by ligi** [comment]
Thanks for the fast reply but I really needed it now and implemented it as a separate plugin written in Kotlin https://github.com/ligi/VectorDrawableImport - this way It is really small and I could develop it fast

**Comment by winterDroid** [comment]
@ligi, @benpye done. Once #133 was build, I will release a new plugin version
