### ISSUE TITLE
Material Asset section always says 0 drawable

### ISSUE THREAD

**Issue by sunilpwyd** [winterDroid/android-drawable-importer-intellij-plugin#61]
![image](https://cloud.githubusercontent.com/assets/6550953/8409468/c1fbdbee-1e95-11e5-9885-3ff37390363a.png)

Even though I am pointing to a correct folder location, the plugin is unable to find the drawables.

**Comment by winterDroid** [comment]
@sunilpwyd there are currently issues known with material icons 2.0. Please consider using an older release which should work fine. I will fix the issues with the next release.
