### ISSUE TITLE
Unexpect black background after importing into Android Studio

### ISSUE THREAD

**Issue by scarletsky** [winterDroid/android-drawable-importer-intellij-plugin#62]
I am trying to import icons from [material-design-icons-2.0.0](https://github.com/google/material-design-icons/releases).

When I import the some white icons into my project, they has unexpect black background.

See the screenshot below.
![39ce529d-ef4a-4b9d-b60f-ded902b36c1d](https://cloud.githubusercontent.com/assets/2386165/8475324/d6ea75e6-20e9-11e5-8394-7354dd1d808e.png)

hdpi, xhdpi, xxhdpi, xxxhdpi are like this: 
![h](https://cloud.githubusercontent.com/assets/2386165/8475327/dd4e39d6-20e9-11e5-9e77-b61ba22ba8a3.png)

but mdpi is normal.
![m](https://cloud.githubusercontent.com/assets/2386165/8475328/e1f600b8-20e9-11e5-986b-7a8bd6abd349.png)

This is the result when I run my project.
![d81dc116-32fc-4aa8-ba8c-8916cbfdc718](https://cloud.githubusercontent.com/assets/2386165/8475325/da14a3c2-20e9-11e5-8460-3dfcb075742b.png)

Is this a bug ?

**Comment by winterDroid** [comment]
Yes this is a bug. But material icons 2.0 is not yet officially supported. Please use an older release of the package. I will add support in the next release.
