### ISSUE TITLE
Plugin Root Entry Failure

### ISSUE THREAD

**Issue by petersmike** [winterDroid/android-drawable-importer-intellij-plugin#63]
Installed the most recent version (downloaded from repository July 8 2015) installed in Android Studio 1.2.2 (June 3 2105 build).  
When I attempt to set the root directory from the Settings--Other Settings - Android Drawable Importer - the Asset Home entry text region continues to enlarge - it is as if it is receiving spaces -  
No action other than Cancel will stop this and I have been unable to enter the Asset home in any way.

Any Ideas of the cause or a work around?
Thank you,

**Comment by winterDroid** [comment]
This is a duplice of #41. There you can find also a https://github.com/winterDroid/android-drawable-importer-intellij-plugin/issues/41#issuecomment-73743360
