### ISSUE TITLE
1-bit color assets are not imported correctly

### ISSUE THREAD

**Issue by jestelle** [winterDroid/android-drawable-importer-intellij-plugin#65]
PNG assets that use 1-bit color are not imported correctly by this plugin.

For example, in the material-design-icons,
ic_stop_white
or
ic_dashboard_white

both exhibit this problem.

The result is the transparent pixels in those icons get rendered as black instead of transparent.

You can see some discussion of this here:
https://github.com/google/material-design-icons/issues/154

**Comment by winterDroid** [comment]
Thanks for reporting! Will fix that with the next release.
