### ISSUE TITLE
Don’t find setting option

### ISSUE THREAD

**Issue by SharerMax** [winterDroid/android-drawable-importer-intellij-plugin#88]
I do not find setting option to set icon files path 

IDE: Android Studio 1.4

**Comment by winterDroid** [comment]
... because I removed them. The packs are now bundled with the plugin.

**Comment by SharerMax** [comment]
...But, I can't use *Icons Packages Drawable Import* feature because I select it will cause NPE .And I can't use *Batch Drawable Import* because I can't select file path which i want to import

**Comment by winterDroid** [comment]
Please check #87 - it is probably the same issue. If so, can you attach the requested logs there?

**Comment by SharerMax** [comment]
thanks, It is same issue
