### ISSUE TITLE
Direct import of zips

### ISSUE THREAD

**Issue by paour** [winterDroid/android-drawable-importer-intellij-plugin#93]
In the description for the plugin, you write "Ever got a zip with drawables for your Android project by your designer with the following structure?". I do, all the time :-)

But the current version of the plugin seems to require unzipping the archive and then dragging each file to the multi-source drawable import window. Wouldn't it be nice if I could just drag the zip and it would populate all the files, or manually unzip, but when I drag the first file, the plugin automatically finds the other resolutions?

**Comment by paour** [comment]
cc @xalep

**Comment by winterDroid** [comment]
Good idea. The problem is that probably every designer uses different namings. So how should I detect the suitable files? I could do simple contains "-xhdpi" checks for example.

**Comment by paour** [comment]
Yes, `-` and `_` seem like reasonable separators. Great plugin btw :-)

**Comment by winterDroid** [comment]
Thanks :+1: Will think about a suitable solution.

**Comment by paour** [comment]
You rock, thanks for the latest update!
