### ISSUE TITLE
Add Batch Drawable in the Newest Version(0.3.2) doesn't Work Exactly in Android Studio.

### ISSUE THREAD

**Issue by Syehunter** [winterDroid/android-drawable-importer-intellij-plugin#95]
When press the "Add" Button, it can only show images under the root directory.
![](http://7xn4z4.com1.z0.glb.clouddn.com/drawable%20importer%20bug.jpg)

**Comment by winterDroid** [comment]
This is a duplicate of #94

**Comment by winterDroid** [comment]
I just uploaded a new release to the JetBrains plugin repository. Hopefully it will be published by them soon.
