### ISSUE TITLE
Cannot select file path

### ISSUE THREAD

**Issue by sheungon** [winterDroid/android-drawable-importer-intellij-plugin#97]
![cannot_select_path](https://cloud.githubusercontent.com/assets/13306724/10761620/2e03df2e-7cfd-11e5-8ca6-c22617d4ce53.jpg)

I was trying to import image by "Batch Drawable Importer".
But I cannot expand any of the folder which trying to select image. See the image attached.
This problem was not happened in version 0.2.X

**Comment by winterDroid** [comment]
Duplicate of #94

**Comment by winterDroid** [comment]
I just uploaded a new release to the JetBrains plugin repository. Hopefully it will be published by them soon.
